### ISSUE TITLE
Error occurred while restoring NuGet packages: The operation failed as details for project x could not be loaded

### ISSUE THREAD

**Issue by Rfaering** [ligershark/sidewafflev2#43] opened 2019-05-07 12:33 UTC
Getting the following error

Error occurred while restoring NuGet packages: The operation failed as details for project x could not be loaded.

After creating empty dotnet projects through template. 

This issue is resolved after restarting visual studio. 

I get this in VS 15.9.11

![image](https://user-images.githubusercontent.com/3888638/57299344-95327380-70d4-11e9-9406-8f1b781d1eaa.png)

Also get the following error when I try to edit the csproj file without unloading it 

![image](https://user-images.githubusercontent.com/3888638/57305765-d8471380-70e1-11e9-9ce9-ee0ec0455c2d.png)

**Comment by Rfaering** [comment] 2019-05-07 13:07
This issue is also fixed, if I run dotnet restore from the folder. Is there any way I can force the template to run dotnet restore after creating?

**Comment by sayedihashimi** [comment] 2019-05-07 19:26
@Rfaering can you give me some steps to reproduce the issue?

**Comment by Rfaering** [comment] 2019-05-07 19:49
@sayedihashimi  - Thanks for your response, I have created the smallest possible example. That reproduces the error on my visual studio. I have also tried to distribute the package to other machines, that experiences the same error after creating the template

Please let me know, if you need further information to reproduce the error

[VsixTest.zip](https://github.com/ligershark/sidewafflev2/files/3154297/VsixTest.zip)

**Comment by Rfaering** [comment] 2019-05-09 14:08
@sayedihashimi - any news?

**Comment by sayedihashimi** [comment] 2019-05-15 22:18
@Rfaering sorry for the delay, I've been too tired due to taking care of a newborn. How did you create this project? When I tried it I'm getting a build error:

```
1>C:\Program Files\dotnet\sdk\2.2.204\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(208,5): error NETSDK1004: Assets file 'C:\Users\sayedha\source\repos\foobar1\foobar1\foobar1\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
1>Done building project "foobar1.csproj" -- FAILED.
```

I tried installing the latest .NET Core 2.2 SDK but that didn't help.

FYI I think I've seen this error message before. I tried to find the issue here but wasn't able to. The error is thrown by VS itself, not SideWaffle.

**Comment by sayedihashimi** [comment] 2019-05-15 22:20
@seancpeters does the error message in the dialog mean anything to you? I know I've seen it before but was not able to track it down.

**Comment by sayedihashimi** [comment] 2019-05-15 22:21
@Rfaering are you using Azure DevOps? I found this issue https://developercommunity.visualstudio.com/content/problem/398508/value-cannot-be-null-parameter-name-punk-when-chec.html

**Comment by seancpeters** [comment] 2019-05-15 22:29
@sayedihashimi - I don't think I've seen this error before.

**Comment by sayedihashimi** [comment] 2019-05-15 23:22
@seancpeters thanks

**Comment by Rfaering** [comment] 2019-05-20 09:13
@sayedihashimi - I did some more testing today, I had used this guide for inspiration for getting my template to work with multiple projects 

https://github.com/ligershark/sidewafflev2/wiki/How-to-Create-A-Multi-Project-Template

Whenever I created standard projects, I kept getting the same issue whenever I created a core project

Playing around with different ideas, I did find a fix though, doing the followings

![image](https://user-images.githubusercontent.com/3888638/58010124-17b52d00-7af0-11e9-883f-2b1b2ecc5c60.png)

Thanks for your help, you can close this issue if you want

**Comment by sayedihashimi** [comment] 2019-05-20 19:02
Glad you got it working, closing.

**Closed by sayedihashimi** 2019-05-20 19:02 UTC
