### ISSUE TITLE
VSIX not found

### ISSUE THREAD

**Issue by jskeet** [ligershark/sidewafflev2#48] opened 2020-04-09 06:38 UTC
The VS marketplace refers to http://sidewaffle.com/feed/web/SideWaffle.Creator.v1.1.vsix, but I can't find _any_ content on sidewaffle.com

Is this project still alive? If so, where would we get the VSIX these days?

**Comment by sayedihashimi** [comment] 2020-04-09 15:23
@madskristensen are you hosting sidewaffle.com or am I?

**Comment by madskristensen** [comment] 2020-04-09 16:46
@sayedihashimi I just checked and I'm not hosting it

**Comment by madskristensen** [comment] 2020-04-09 16:46
@sayedihashimi you are

**Comment by sayedihashimi** [comment] 2020-04-09 17:20
@madskristensen thanks, let me take a look to see what can be happening here.

**Comment by sayedihashimi** [comment] 2020-04-09 21:15
For the time being you can download from the following URL

https://github.com/ligershark/SideWaffleWebsite/blob/master/SideWaffleWebsite/feed/web/SideWaffle.Creator.v1.1.vsix

**Comment by jskeet** [comment] 2020-04-09 21:19
Great, thank you very much. (You might want to consider using https://github.com/ligershark/sidewafflev2/releases as an alternative place for release downloads)

**Comment by avrahamcool** [comment] 2020-09-13 20:14
also, you need to fix the link from the marketplace.

**Comment by sayedihashimi** [comment] 2020-09-14 16:45
The links are correct, the problem is that the site is not running. My Azure account was disabled for some reason. I'm trying to get it back up and running. In the mean time there is a link in my previous command that can be used.

**Comment by sayedihashimi** [comment] 2021-01-29 16:28
Fixed a while ago closing

**Closed as completed by sayedihashimi** 2021-01-29 16:28 UTC
