### ISSUE TITLE
Template Pack project with multiple templates installs same template multiple times

### ISSUE THREAD

**Issue by ccheetham** [ligershark/sidewafflev2#35] opened 2018-06-22 15:35 UTC
I've a solution with a couple of projects, lets call them Foo and Bar, for which I've created templates (ie, .template.config dirs.).  I then create a Template Pack Project Template in the solution.  When I run the template pack project, I do see both Foo and Bar templates in the test VS2017 instance.  However, both templates create projects of the Foo type.

Note this isn't a multi-project template.  Each project is standalone.

**Comment by sayedihashimi** [comment] 2018-06-22 17:46
@ccheetham can you attach a sample that reproduces the issue?

**Comment by ccheetham** [comment] 2018-06-22 17:53
https://github.com/SteeltoeOSS/Samples/tree/skunkworks-sdk/Configuration/src/AspDotNetCore

**Comment by sayedihashimi** [comment] 2018-06-22 17:58
@ccheetham I don't see any .vstemplate file in that repository.

**Comment by ccheetham** [comment] 2018-06-22 18:03
Note sure I understand exactly what you're referring to.

There are 2 .vstemplate files:
Simple/.template.config/template.vstemplate
SimpleCloudFoundry/.template.config/template.vstemplate

**Comment by sayedihashimi** [comment] 2018-06-22 18:58
I was looking at the wrong branch on my local machine.

So I'm able to reproduce the issue. For some reason it's using the same .vstemplate file for both projects. It seems there is some bug in the .targets file here.

**Comment by sayedihashimi** [comment] 2018-06-22 19:05
OK I found out what was happening. The names of both `.vstemplate` files was `template.vstemplate`. They need to be unique across the solution. I've sent a PR to your project to fix the issue https://github.com/SteeltoeOSS/Samples/pull/46. I'll close this, since I believe it's fixed, but if you still have any issues please reopen this.

**Comment by sayedihashimi** [comment] 2018-06-22 19:06
@tylerbhughes can you add a note that the names of the `.vstemplate` files need to be unique across the solution to the docs?

**Closed by sayedihashimi** 2018-06-22 19:05 UTC

**Comment by ccheetham** [comment] 2018-06-22 19:16
Confirming that your suggestion worked.  Thanks for the speedy response/resolution!

**Comment by sayedihashimi** [comment] 2018-06-22 19:58
@ccheetham great, thanks for letting us know it's working for you and thanks for using SideWaffle (I still love that name!).
