### ISSUE TITLE
Guidance on creating multi-project template with specific structure

### ISSUE THREAD

**Issue by giggio** [ligershark/sidewafflev2#25] opened 2017-11-23 21:21 UTC
I am having some trouble creating a multi-project template and I would like your recommendation on how to proceed, so I don't fight the tools.

What I want is that the final project structure on disk looks like this:

````
\MyProject.sln
\src\MyProject.WebApp\MyProject.WebApp.csproj
\test\MyProject.UnitTests\MyProject.UnitTests.csproj
````

And I want my solution to have 2 solution folders, `src`  and `test` that map to the directories on disk, with each project in the correct solution folder.

Right now I created the template pack project file root folder, so the template structure looks like this:

````
\MyTemplate.sln
\MyTemplate.Pkg\MyTemplate.Pkg.csproj
\.template.config\
\src\MyTemplate.WebApp\MyTemplate.WebApp.csproj
\test\MyTemplate.UnitTests\MyTemplate.UnitTests.csproj
````

My `template.json` is referencing the two `.csproj` files correctly.

I am having all sorts of trouble because of this. If I create a new project called `MyProject` I am getting an extra `MyProject` folder created and I also get two `.sln` files created, one on root, the other on the `MyProject` directory. Only the second one actually has the solution folders.
Structure ends up like this:

````
\MyProject.sln
\MyProject\MyProject.sln
\MyProject\src\MyProject.WebApp\MyProject.WebApp.csproj
\MyProject\test\MyProject.UnitTests\MyProject.UnitTests.csproj
````

So, how should I proceed? Is there any config I need to change?
Thanks in advance.

**Comment by Advitalitum** [comment] 2017-12-01 09:05
I have same problem. Also solution folders structure not saved in \MyProject.sln but it is in \MyProject\MyProject.sln. Solution in \MyProject\MyProject.sln is a clone of original solution. It has reference to template csproj file. \MyProject\ folder also contains folder with template project.

**Comment by giggio** [comment] 2017-12-01 18:39
@sayedihashimi Can you give us a hand here? Thanks!

**Comment by Advitalitum** [comment] 2017-12-18 13:58
@giggio 
Found solution. You can create [**custom wizard**](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-wizards-with-project-templates). In .template.config\template.vstemplate place custom wizard before default wizard:
```xml
<!-- Custom Wizard -->
  <WizardExtension>
    <Assembly>YourTemplate, Version=1.0.0.0, Culture=Neutral, PublicKeyToken=token</Assembly>
    <FullClassName>YourTemplate.CustomWizard</FullClassName>
  </WizardExtension>
  <!-- Default Wizard -->
  <WizardExtension>
    <Assembly>Microsoft.VisualStudio.TemplateEngine.Wizard, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a</Assembly>
    <FullClassName>Microsoft.VisualStudio.TemplateEngine.Wizard.TemplateEngineWizard</FullClassName>
  </WizardExtension>
```
Create field in custom wizard:
```csharp
private string oldDestinationDirectory;
```
Place this to RunStarted method:
```csharp
oldDestinationDirectory = replacementsDictionary["$destinationdirectory$"];
// Dirty hack here
var newDestinationDirectory = Path.Combine($"{replacementsDictionary["$destinationdirectory$"]}", @"..\");
replacementsDictionary["$destinationdirectory$"] = Path.GetFullPath(newDestinationDirectory);
```
in RunFinished:
```csharp
Task.Run(() =>
{
    if (Directory.Exists(oldDestinationDirectory))
    {
        Directory.Delete(oldDestinationDirectory);
    }
});
```
You also may need to add references to System.IO and System.Threading.Tasks etc

**Comment by Advitalitum** [comment] 2017-12-20 10:16
Found dirty hack for preserving folder structure.
# **MAYBE IT IS DANGEROUS** #
We will preserve old solution file and open it on project creation.

Remove "SolutionFile.sln" from exclude section in .template.config\template.json. In SolutionFile.sln wrap project section with project template by #if (false), #endif :
```
#if (false)
Project("{FAE04EC0-301F-11D3-BF4B-00C12379EFBC}") = "YourTemplateProject", "YourTemplateProject", "{41CFBEEE-FEC0-42C3-B1AF-4BF82A132113}"
EndProject
#endif
```
- - - - 
Add two wizards. One before default wizard, one after.
```xml
<!-- BeforeWizard -->
<WizardExtension>
  <Assembly>YourTemplate, Version=1.0.0.0, Culture=Neutral, PublicKeyToken=token</Assembly>
  <FullClassName>YourTemplate.BeforeWizard </FullClassName>
</WizardExtension>
<!-- Default Wizard -->
<WizardExtension>
  <Assembly>Microsoft.VisualStudio.TemplateEngine.Wizard, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a</Assembly>  <FullClassName>Microsoft.VisualStudio.TemplateEngine.Wizard.TemplateEngineWizard</FullClassName>
</WizardExtension>
<!-- AfterWizard -->
<WizardExtension>
  <Assembly>YourTemplate, Version=1.0.0.0, Culture=Neutral, PublicKeyToken=token</Assembly>
  <FullClassName>YourTemplate.AfterWizard </FullClassName>
</WizardExtension>
```
- - - -
In Runstarted method of BeforeWizard place:
```csharp
// Close new solution
var dte = (DTE) automationObject;
var solution = (Solution2) dte.Solution;
solution.Close();

// Delete old directory(in my case VS creating it) and change destination
var oldDestinationDirectory = replacementsDictionary["$destinationdirectory$"];
if (Directory.Exists(oldDestinationDirectory))
    {
        Directory.Delete(oldDestinationDirectory, true);
    }

var newDestinationDirectory = Path.Combine($"{oldDestinationDirectory}", @"..\");
replacementsDictionary["$destinationdirectory$"] = Path.GetFullPath(newDestinationDirectory);
```
- - - - 
In AfterWizard:
```csharp
private DTE dte;

private string destinationDirectory;

private string solutionName;

public void RunStarted(object automationObject,
    Dictionary<string, string> replacementsDictionary,
    WizardRunKind runKind, object[] customParams)
{
    dte = (DTE) automationObject;
    destinationDirectory = replacementsDictionary["$destinationdirectory$"];
    solutionName = replacementsDictionary["$safeprojectname$"];
}

public void RunFinished()
{
    // Open "old" solution
    var solution = (Solution2)dte.Solution;
    var pathToOldSolution = Path.Combine(destinationDirectory, solutionName + ".sln");
    solution.Open(pathToOldSolution);
}
```
So, it works well but i don't know what kind of side-effects may appear with copying old sln file.

**Comment by sayedihashimi** [comment] 2018-03-26 19:47
I believe that [this comment](https://github.com/dotnet/templating/issues/1452#issuecomment-375105238) from a dev on the team addresses this issue. Can you take a look and let me know if that is what you're looking for?

**Comment by giggio** [comment] 2018-04-12 21:26
@sayedihashimi it works, the physical folder structure is as expected.
But I lost my solution folders from the original solution. Is there a way to get it back?
BTW, it would be a good idea to share how to fix this, step by step, in a wiki, etc, that is discoberable. Or maybe bake the solution into Sidewaffle.
@Advitalitum thanks for the help, but @sayedihashimi solution was simpler. Only one wizard. :)

**Comment by sayedihashimi** [comment] 2018-04-13 15:32
@giggio Solution Folders are not supported. To create solution folders you'll need a custom wizard to handle creating those and placing projects inside of them.

**Comment by giggio** [comment] 2018-06-06 15:35
@tylerbhughes yes, the response from Sayed above helped: https://github.com/ligershark/sidewafflev2/issues/25#issuecomment-376288902

**Comment by tylerbhughes** [comment] 2018-06-06 16:20
Great, I'll close this then since it's been resolved.

**Closed by tylerbhughes** 2018-06-06 16:20 UTC

**Comment by giggio** [comment] 2018-06-13 21:54
Great, but it would be nice to post a more structured guidance somewhere, probably on some docs or on the readme.

**Comment by tylerbhughes** [comment] 2018-06-13 22:29
@giggio Thanks for the input. We're still working on documentation. It's just a slow process.

**Comment by KKacer** [comment] 2019-03-10 21:47
@Advitalitum Did your solution work?

**Comment by avrahamcool** [comment] 2019-03-10 21:57
@KKacer I can confirm that this solution works.
you can take a look at my VS addon [here](https://github.com/avrahamcool/Aleph1.Skeletons)

what I did was to create a new class library beside the packager project - to hold the wizards.
(I have 2 set of wizards because my addon adds 2 different multilayered projects skeletons) 
then have the packager project reference the wizards project.

also, in the directory of the "main" solution - I have child directories.
in each one I have a solution with a complete hierarchy of projects.
each one of them is bundled differently as a template.

I hope that the source code can help you get were you need.

**Comment by KKacer** [comment] 2019-03-12 15:09
@avrahamcool
Great!
Will take a look at your project ASAP.
Yeah I hope so.

**Comment by KKacer** [comment] 2019-03-12 15:39
@avrahamcool 
Watched that, awesome! the Wizard seems to be what I wanted, the result in your final distributed VSix also looks cool and as expected.
Still I have some problems and questions related to it, 
maybe you would like to give me a help. Can we discuss a bit regarding this in Skype/Discord, ...? 
S-ID: Kasra.Kacer
Guess 5 minutes could be enough.

**Comment by avrahamcool** [comment] 2019-03-12 16:32
Hi @KKacer I'll try to help.
Let's take it to a private channel via email (can be found in my user profile)
